FROM registry.access.redhat.com/ubi10@sha256:6e3f045f5380e8d8dffaea7e01bf926d2db44aff751048697e780d1253687843

# Test disabled network access
RUN if getent hosts www.google.com; then echo "Has network access!"; exit 1; fi

# Install dependencies from RPM lockfile
RUN dnf -y install golang npm

WORKDIR /src/gomod-package
RUN . /tmp/hermeto.env && go build

WORKDIR /src/npm-package
RUN . /tmp/hermeto.env && npm install
